version: "3"
services:
  app:
    container_name: go
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - api_postgres
    networks:
      - gonetwork

  api_postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
      #- ./postgres:/var/lib/postgresql/data, se quiser DB dentro da pasta do projeto
    networks:
      - gonetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - api_postgres
    ports:
      - "5050:80"
    networks:
      - gonetwork
    restart: unless-stopped

volumes:
  api:
  database_postgres:

networks:
  gonetwork:
    driver: bridge
