apiVersion: v1
kind: Service
metadata:
  name: books # Nome to aplicativo
  labels:
    app: books # Nome to aplicativo
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: books # Nome to aplicativo
    tier: postgres
