apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: local
    app: books # Nome to aplicativo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
