apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  labels:
    app: books # Nome to aplicativo
spec:
  # storageClassName: manual # quando passar para um serviço Cloud, é aqui que será fornecido o endereço de acesso.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
