apiVersion: v1
kind: Secret
data:
  API_SECRET: b2pHaGZlNlc1YjI0
  POSTGRES_USER: cm9kcmlnb3ZhbGVudGU=
  POSTGRES_PASSWORD: R3VzdGF2bzIwMTI=
  POSTGRES_DB: Ym9va3M=
  DB_HOST: cG9zdGdyZXMtY2x1c3Rlci1pcC1zZXJ2aWNl
  DB_DRIVER: cG9zdGdyZXM=
  DB_USER: cm9kcmlnb3ZhbGVudGU=
  DB_PASSWORD: R3VzdGF2bzIwMTI=
  DB_NAME: Ym9va3M=
  DB_PORT: NTQzMg==
metadata:
  name: psql-secret
type: Opaque
# stringData: # We dont need to worry about converting to base64
#   POSTGRES_USER: rodrigovalente
#   POSTGRES_PASSWORD: Gustavo2012
#   POSTGRES_DB: books
#   API_SECRET: ojGhfe6W5b24
#   DB_HOST: books ou postgres-cluster-ip-service
#   DB_DRIVER: postgres

#   DB_USER: rodrigovalente
#   DB_PASSWORD: Gustavo2012
#   DB_NAME: books
#   DB_PORT: 5432
